In [4]:
import networkx as nx
import numpy as np
from numpy.random import default_rng
rng = default_rng(seed=111)
#from timeawarepc.tpc import cfc_tpc, cfc_pc, cfc_gc
from timeawarepc.simulate_data import *
from timeawarepc.find_cfc import *

# Load Pandas and Matplotlib

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

Now load the Power 2011 parcellation

In [6]:
power = pd.read_csv("../rsfmri/bin/power_2011.csv")
power

,ROI,X,Y,Z,Network,Color,NetworkName,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,1,-25,-98,-12,-1,White,Uncertain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,27,-97,-13,-1,White,Uncertain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,24,32,-18,-1,White,Uncertain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,-56,-45,-24,-1,White,Uncertain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,8,41,-24,-1,White,Uncertain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,260,-27,-71,37,12,Green,Dorsal attention,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,-32,-1,54,12,Green,Dorsal attention,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,262,-42,-60,-9,12,Green,Dorsal attention,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,263,-17,-59,64,12,Green,Dorsal attention,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,264,29,-5,54,12,Green,Dorsal attention,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

For each ROI in Power, load the corresponding timeseries for Subject 001

In [7]:
data = []
for roi in list(power['ROI']):
    entry = power.loc[power['ROI'] == roi]
    net = int(entry['Network'])
    net = max(0, net)
    mat = pd.read_csv("../rsfmri/sub-001/func/region_%03d_network_%02d.txt" % (roi, net), delim_whitespace=True)
    vec = np.mean(mat, axis=0)
    row = list(vec)
    data.append(row)

Turn data in t X p array

In [8]:
mdata = np.array(data)
mdata

array([[25270.275875 , 25326.054375 , 25263.3245   , ..., 25411.98925  ,
        25546.183    , 25594.22025  ],
       [23474.168875 , 23452.242    , 23492.779375 , ..., 23475.32275  ,
        23650.298875 , 23576.946625 ],
       [13048.485125 , 13024.3963   , 13067.5673125, ..., 13476.2212125,
        13456.5293   , 13378.3766625],
       ...,
       [22508.948125 , 22498.85275  , 22533.179125 , ..., 22551.441625 ,
        22650.69275  , 22621.614125 ],
       [20713.48675  , 20728.48     , 20768.13125  , ..., 20914.06375  ,
        21279.663625 , 20829.01125  ],
       [19048.081625 , 19003.668625 , 18929.843875 , ..., 18995.1605   ,
        19008.108375 , 18979.892125 ]])

 Plot the data for inspection

# Run TCP

In [ ]:
model = 'lingauss'
method_name = 'TPC'
alpha = 0.05
maxdelay=1
isgauss = (model == 'lingauss')
adjmat, causaleffmat = find_cfc(mdata,method_name,alpha=alpha,maxdelay=maxdelay,isgauss=isgauss)